### ISSUE TITLE
Use "hashicorp/precise32" instead of "precise32" from vagrantup.com.

### ISSUE THREAD

**Issue by drm2** [semmypurewal/node-dev-bootstrap#16]
I just noticed that running `vagrant up` on this file caused me to download a new copy of precise32 because this Vagrantfile doesn't use "hashicorp/precise32" which is the official box name. They are the same, but not using the vendor name caused it to re-download the box. Is there a good reason for not using "hashicorp/precise32"? Thanks!

**Comment by semmypurewal** [comment]
This project was created before hashicorp existed, so it's probably leftover from awhile ago.

I can fix it this weekend, or you can submit a pull request which I can merge this weekend after confirming it works.

Thanks!

**Comment by semmypurewal** [comment]
Switched to using the latest trusty image from Ubuntu, so this should be resolved now!
