### ISSUE TITLE
Cookbooks not working with VB 5.0.14 and vagrant 1.81

### ISSUE THREAD

**Issue by marcusams** [semmypurewal/node-dev-bootstrap#18]
I don't get any of the packages like nodejs, mongodb, redis, mongoose etc and need to install manually - this has worked for the most part but I can't get mongoose working...

**Comment by semmypurewal** [comment]
Hmmm, that's strange. Can you try the latest version of Vagrant (1.8.6)? There was an issue with Vagrant 1.8.5, but it's been resolved now.

**Comment by marcusams** [comment]
Cool, will do. Thanks for the quick response. Love the book btw.

**Comment by marcusams** [comment]
That worked - thanks.  However I did get the following error right at the end of the chef provisioning:
```
==> default: ERROR:  Error installing cf:
==> default: 	json_pure requires Ruby version ~> 2.0.
```
I wasn't able to apt-get install Ruby2.0 and altering the vagrant file did not work either.  I found a means to update on stackoverflow which worked and let me install cf but the login failed for some reason.  I installed locally on my mac and this worked.  Perhaps you can update the vagrant image to include ruby2.0+ for future readers.

Thanks again,

Marcus

**Comment by semmypurewal** [comment]
I've updated the version of Ruby so this should no longer be an issue.
